server:
  port: 8848
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anki?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB
  redis:
    host: localhost
    password: root
    port: 6379
elasticsearch:
  host: localhost
  port: 9200
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志志
  global-config:
      db-config:
        #逻辑删除字段
        logic-delete-field: delFlag
        #删除值为1
        logic-delete-value: 1
        #未删除值为0
        logic-not-delete-value: 0
openai:
  model: ${OPENAI_MODEL:text-davinci-003}
  apiKey: ${OPENAI_API_KEY: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}
wx:
   appId: wxe1d4882a9a94b849
   appSecret: 0e01cb220f5083c01fd523f497f4cb12
   online_people_url: https://api.weixin.qq.com/sns/jscode2session

# 阿里云短信服务
aliyun:
  AccessKeyId: 
  AccessKeySecret: 

# 阿里云云存储OSS配置信息
# Bucket地址
  oss:
    file:
      endpoint: oss-cn-guangzhou.aliyuncs.com
  # Access Key
      keyid: 
      keysecret: 
  # Bucket名称
      bucketname: test-anki
baidu:
#  百度翻译
  fanyi:
    APP_ID: 20230322001610997
    SECURITY_KEY: 
  yuyan:
    App_Key:
    Secret_Key: 
